<link rel="stylesheet" type="text/css" href="https://cdn.seqr.com/webshop-plugin/css/seqrShop.css">

<?php
    echo '<script>'.
            'seqr.id = "' . $this->getOrderId() . '";'.
            'seqr.timeout = ' . $this->getSecondsBeforeCancel() . ' * 1000;'.
        '</script>';
?>

<div style="width: 500px; margin: auto;">
    <?php
        if ($this->getOrderId()) {
            echo '<script id="seqrShop" src="'.$this->getWebPluginUrl().'"></script>';
        } else {
            echo 'Error: SEQR payment temporarily unavailable, please try again later.';
        }
    ?>
</div>
